---

- name: Add opensips-cli repo
  copy:
          content: "{{ debian_repo_fetch }}"
          dest: /etc/apt/sources.list.d/opensips-cli.list

- name: Install opensips-cli
  apt:
          name: opensips-cli
          update_cache: yes
         
