---
- name: Install openSIPS repository
  yum:
          name: '{{ repo | replace(" ", "") }}'
  vars:
          repo: >-
                  {{ opensips_yum_repo }}/{{ opensips_version }}/
                  {{ opensips_build }}/el/{{ ansible_distribution_major_version }}/
                  {{ ansible_architecture }}/opensips-yum-{{ opensips_build }}-
                  {{ opensips_version }}-{{ opensips_yum_release }}.el
                  {{ ansible_distribution_major_version }}.noarch.rpm

          

- name: Install openSIPS-cli
  yum:
          name: opensips-cli
